#
# Docker networks for containers to access internal ports.
#
networks:
  # Default docker network for App services. Set up as
  # an external network so need to run:
  # ~>  docker network create app-net
  app-net:
    external: true
  #
  # Exclusive Gitea network for DB comms
  # ...is also external so:
  # ~> docker network create db-net
  db-net:
      external: true
  #
  # Exclusive Portainer Agent network
  # ...external so:
  # ~> docker network create port-net
  port-net:
      external: true
#
# Container configuration section
#
services:
  #
  # Privatebin a secure pastebin web service running locally
  #
  privatebin:
    image: privatebin/nginx-fpm-alpine
    container_name: privatebin
    restart: always
    privileged: false
    ports:
      - "8880:8080"
    networks:
      - app-net
    volumes:
      - ${PWD}/privatebin:/srv/data
    environment:
      - TZ=America/Los_Anglese
  #
  # Portainer for managing attack machines, ephemeral and persistent, as well as shell listeners
  # 
  portainer:
    image: portainer/portainer-ce:2.20.3-alpine #Alpine is a lightweight, low impact OS
    container_name: portainer
    restart: always
    ports:
      - "9815:9000" # HTTP
      - "8000:8000" # Edge connect port
      - "9443:9443" # HTTPS
    networks:
      - port-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/portainer/data:/data
  #
  # Homarr dashboard service for creating a central team hub webapp
  #
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:0.15.3
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ${PWD}/homarr/configs:/app/data/configs
      - ${PWD}/homarr/icons:/app/public/icons
      - ${PWD}/homarr/data:/data
    environment:
      # Wat a journey this was...i don't want to talk about rn.
      - DEFAULT_COLOR_SCHEME=dark
      - AUTH_PROVIDER=credentials,oidc
      - AUTH_LOGOUT_REDIRECT_URL=http://team.buckfiddy/auth/login?redirectAfterLogin=/board
      - AUTH_OIDC_AUTO_LOGIN=false
      - AUTH_OIDC_OWNER_GROUP=b_admin
      - AUTH_OIDC_ADMIN_GROUP=b_admin
      - NEXTAUTH_URL=http://team.buckfiddy/
      - NEXTAUTH_SECRET=${NXT_SECRET}
      - AUTH_OIDC_URI=https://buckfiddy.westus2.cloudapp.azure.com/auth/realms/buck50
      - AUTH_OIDC_CLIENT_SECRET=${OIDC_SECRET}
      - AUTH_OIDC_CLIENT_ID=${OIDC_ID}
      - AUTH_OIDC_CLIENT_NAME=SSO Login
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - NODE_VERSION=20.2.0
      - YARN_VERSION=1.22.19
      - NEXT_TELEMETRY_DISABLED=1
      - NODE_ENV=production
      - NODE_OPTIONS=--no-experimental-fetch
      - PORT=7575
      - DATABASE_URL=file:/data/db.sqlite
    ports:
      - '7575:7575'
    tty: true
    stdin_open: true
    networks:
      - app-net
  #
  # Gitea: For keeping code safe 'n stuff...
  # Guides:
  #   - docs.gitea.com (source): https://docs.gitea.com/installation/install-with-docker
  # Exception: Using go-gitea repo cuz it's written in Go
  gitea:
    image: 'gitea/gitea:1.22.1'
    container_name: gitea
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "8122:22"
    volumes:
      - ${PWD}/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      # Setting user/grou IDs
      - USER_UID=1000
      - USER_GID=1000
      # Database backend
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgre-tdb
      - GITEA__database__NAME=${GITEA_DB}
      - GITEA__database__USER=${GITEA_DB_USER}
      - GITEA__database__PASSWD=${GITEA_DB_PASSWORD}
    depends_on:
      - postgre-tea_db   
    security_opt:
      - no-new-privileges:true
    networks:
      - db-net
      - app-net
  #
  # Postgresql database for the Gitea container
  # 
  postgre-tea_db:
    image: postgres:14
    container_name: postgre-tdb
    restart: always
    environment:
      - POSTGRES_USER=${GITEA_DB_USER}
      - POSTGRES_PASSWORD=${GITEA_DB_PASSWORD}
      - POSTGRES_DB=${GITEA_DB}
    networks:
      - db-net
    volumes:
      - ${PWD}/gitea/gitdb:/var/lib/postgresql/data
